services:
  - type: web
    name: poopbackend
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SERVER_ADDRESS
        value: 0.0.0.0